openapi: 3.0.3
info:
  title: API per ChronoBus
  version: 1.0.0

paths:
  /reports:
    get:
      summary: Get all reports
      responses:
        '200':
          description: List of all reports
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Report'

    post:
      summary: Create a new report
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewReport'
      responses:
        '201':
          description: Report created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Invalid input
        '500':
          description: Server error

  /reports/{id}:
    get:
      summary: Get a report by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Report found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report'
        '404':
          description: Report not found
        '500':
          description: Server error

    delete:
      summary: Delete a report by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Report deleted successfully
        '404':
          description: Report not found
        '500':
          description: Server error

components:
  schemas:
    Report:
      type: object
      properties:
        _id:
          type: string
        line:
          type: string
        time:
          type: integer
          description: UNIX timestamp
        crowdedness:
          type: string
          enum: [low, medium, high]
        __v:
          type: integer
      required: [_id, line, time, crowdedness]

    NewReport:
      type: object
      properties:
        line:
          type: string
        time:
          type: integer
          description: UNIX timestamp
        crowdedness:
          type: string
          enum: [low, medium, high]
      required: [line, time, crowdedness]
